# Generated by Django 5.1.2 on 2024-10-11 17:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='about_user',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='created_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='orders_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='orders_now',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='password_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
        migrations.AddField(
            model_name='user',
            name='wish_list',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shop_name', models.CharField(max_length=255, unique=True)),
                ('shop_image', models.ImageField(blank=True, null=True, upload_to='shops/')),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='shop_logos/')),
                ('shop_background_image', models.ImageField(blank=True, null=True, upload_to='shop_backgrounds/')),
                ('shop_identity_colours', models.JSONField(blank=True, default=list, null=True)),
                ('shop_selling_categories', models.JSONField(default=list)),
                ('best_sellers', models.JSONField(default=list)),
                ('shop_views', models.IntegerField(default=0)),
                ('shop_reviews_is_on', models.BooleanField(default=True)),
                ('monthly_sold_items', models.IntegerField(default=0)),
                ('profit_this_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('profit_last_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('profit_this_year', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shop_created_at', models.DateTimeField(auto_now_add=True)),
                ('about_shop', models.TextField(blank=True, null=True)),
                ('how_old_is_the_shop', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('shop_physical_address', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_items_adders', models.ManyToManyField(blank=True, related_name='added_items_shops', to=settings.AUTH_USER_MODEL)),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_shops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=500)),
                ('long_description', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('how_many_sold', models.IntegerField(default=0)),
                ('how_many_views', models.IntegerField(default=0)),
                ('reviews', models.JSONField(default=list)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('item_images', models.JSONField(default=list)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('is_free_shipping', models.BooleanField(default=False)),
                ('price_history', models.JSONField(default=list)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.shop')),
            ],
        ),
    ]
