# Generated by Django 5.1.2 on 2024-10-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_shop_best_sellers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='shop_categories', to='core.category'),
        ),
    ]
