# Generated by Django 5.1.2 on 2024-10-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20241011_1752'),
    ]

    operations = [
    ]
