# Generated by Django 5.1.2 on 2024-10-11 18:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20241011_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_identity_colours',
            new_name='shop_identity_colors',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=500)),
                ('long_description', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('how_many_sold', models.IntegerField(default=0)),
                ('how_many_views', models.IntegerField(default=0)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('is_free_shipping', models.BooleanField(default=False)),
                ('price_history', models.JSONField(default=list)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('review_images', models.JSONField(blank=True, default=list)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.product')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
