# Generated by Django 5.1.2 on 2024-10-12 14:13

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_shop_identity_colours_shop_shop_identity_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='how_old_is_the_shop',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='profit_last_month',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shop_background_image',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shop_reviews_is_on',
        ),
        migrations.AlterField(
            model_name='shop',
            name='monthly_sold_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_identity_colors',
            field=models.JSONField(blank=True, default=list, help_text="A list of up to 3 colors representing the shop's identity.", null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_image',
            field=models.ImageField(blank=True, null=True, upload_to='shops/', validators=[core.validators.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/', validators=[core.validators.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='about_user',
            field=models.TextField(blank=True, help_text='A personal description of the user.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/', validators=[core.validators.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
