name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test
        working-directory: ./back-end
        run: |
          docker-compose up -d db  # Start db in detached mode
          docker-compose run --rm app sh -c "
            until pg_isready -h db -p 5432 -U devuser; do
              echo 'Waiting for PostgreSQL...';
              sleep 1;
            done &&
            python manage.py wait_for_db &&
            python manage.py test"

      - name: Lint
        working-directory: ./back-end # Change to the back-end directory
        run: docker-compose run --rm app sh -c "pycodestyle ."
